# Set up notification options
sudo: required
addons:
  chrome: stable
notifications:
  email:
    recipients:
    - peter.nieuwenhuyse@gmail.com
    on_success: change
    on_failure: always
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  -   ng build --prod --aot
deploy:
  provider: heroku
  api_key:
    secure: heroku
  app: ngrx-demo-app

